export const API_DATA = {
	axes_val: {
		y: {
			min: 0,
			max: 10,
		},
		x: {
			min: 0,
			max: 800000,
		},
	},
	data: [
		{
			label: 'Black Panther',
			rating: 7.4,
			gross: 700059,
			is_local: false,
			genre: 'superhero',
		},
		{
			label: 'Avengers: Infinity War',
			rating: 8.5,
			gross: 678815,
			is_local: false,
			genre: 'superhero',
		},
		{
			label: 'Incredibles 2',
			rating: 7.8,
			gross: 608581,
			is_local: false,
			genre: 'superhero',
		},
		{
			label: 'Jurassic World: Fallen Kingdom',
			rating: 5,
			gross: 456582,
			is_local: false,
			genre: 'action',
		},
		{
			label: 'Deadpool 2',
			rating: 7.8,
			gross: 318491,
			is_local: false,
			genre: 'superhero',
		},
		{
			label: "Dr. Seuss' The Grinch",
			rating: 6.4,
			gross: 261335,
			is_local: false,
			genre: 'musical',
		},
		{
			label: 'Mission: Impossible - Fallout',
			rating: 7.9,
			gross: 220159,
			is_local: false,
			genre: 'action',
		},
		{
			label: 'Ant-Man and the Wasp',
			rating: 7.2,
			gross: 216648,
			is_local: false,
			genre: 'superhero',
		},
		{
			label: 'Venom',
			rating: 6.8,
			gross: 213205,
			is_local: false,
			genre: 'superhero',
		},
		{
			label: 'A Star is Born',
			rating: 8.1,
			gross: 200539,
			is_local: false,
			genre: 'musical',
		},
		{
			label: 'Bohemian Rhapsody',
			rating: 8.3,
			gross: 786856,
			is_local: false,
			genre: 'musical',
		},
		{
			label: 'Crazy Rich Asians',
			rating: 7.1,
			gross: 174016,
			is_local: false,
			genre: 'comedy',
		},
		{
			label: 'Ralph Breaks the Internet',
			rating: 7.4,
			gross: 169181,
			is_local: false,
			genre: 'comedy',
		},
		{
			label: 'Halloween',
			rating: 2.9,
			gross: 159326,
			is_local: false,
			genre: 'drama',
		},
		{
			label: 'The Meg',
			rating: 3.8,
			gross: 145443,
			is_local: false,
			genre: 'action',
		},
		{
			label: "Ocean's 8",
			rating: 1.2,
			gross: 700218,
			is_local: false,
			genre: 'action',
		},
		{
			label: 'Ready Player One',
			rating: 7.5,
			gross: 137690,
			is_local: false,
			genre: 'action',
		},
		{
			label: 'Aquaman',
			rating: 7.6,
			gross: 137235,
			is_local: false,
			genre: 'superhero',
		},
		{
			label: 'Tiempo de Valientes',
			rating: 7.3,
			gross: 240254,
			is_local: true,
			genre: 'comedy',
		},
		{
			label: 'Nueve Reinas',
			rating: 9.1,
			gross: 450654,
			is_local: true,
			genre: 'crime',
		},
		{
			label: 'El secreto de sus ojos',
			rating: 8.7,
			gross: 585000,
			is_local: true,
			genre: 'drama',
		},
	],
};
